### ISSUE TITLE
How to make a difference compared to iBeacon

### ISSUE THREAD

**Issue by andersborgabiro** [AltBeacon/spec#14]
Provide the same semantics as in NFC and QR Codes: A free text string (e.g. 100 bytes) for URLs (http:, https:), phone numbers (tel:), SMS (sms:, smsto:), location (geo:), e-mail (mailto:) etc.

The most important would be URLs. Shortened URLs would easily fit in the 20 bytes payload.

Cheers,
Anders

**Comment by mdxs** [comment]
I think this is outside the https://github.com/AltBeacon/spec specification as-is. Perhaps Eddystone-URL is a better fit for your purposes.

**Comment by andersborgabiro** [comment]
A lot has happened since, and Eddystone-URL is no doubt the answer today for HTTP. Most beacon providers support both iBeacon and Eddystone, but no other method.

**Comment by mdxs** [comment]
Sure, I was just going through the issues to see if I could answer any.
@andersborgabiro Can you close this issue now that it is answered?
