### ISSUE TITLE
Inaccurate Bluetooth Specification 4.0 Reference 

### ISSUE THREAD

**Issue by d4nc00per** [AltBeacon/spec#17]
The reference to
`Bluetooth Specification Version 4.0, Volume 1, Section 1.2 Overview of Bluetooth Low Energy Operation`
should be 
`Bluetooth Specification Version 4.0, Volume 1, Part A, Section 1.2 Overview of Bluetooth Low Energy Operation`
and
`Bluetooth Specification Version 4.0, Volume 3, Part C, Section 2.3 Advertising Channel PDU`
should be 
`Bluetooth Specification Version 4.0, Volume 6, Part B, Section 2.3 Advertising Channel PDU`

**Comment by davidhelms** [comment]
Weird that I would have messed that up so badly. But thanks for identifying it.
