### ISSUE TITLE
getServiceUuid is not documented

### ISSUE THREAD

**Issue by IgorGanapolsky** [AltBeacon/spec#18]
Hello,
how come Beacon <b>getServiceUuid()</b> is not a publicly documented method?

Igor

**Comment by davidgyoung** [comment]
@IgorGanapolsky, I think you opened this issue against the wrong repo.  Did you mean to open it here?  https://github.com/AltBeacon/android-beacon-library/issues

**Comment by IgorGanapolsky** [comment]
I am looking at your spec: https://github.com/AltBeacon/spec.  What's wrong with opening it there?

**Comment by davidgyoung** [comment]
The Beacon.getServiceUuid() method is part of the other repo I mentioned in my comment.  FYI, I have updated the JavaDocs so you can see the public documentation of that method here:  http://altbeacon.github.io/android-beacon-library/javadoc/org/altbeacon/beacon/Beacon.html

For other issues with this library, please do open an issue at the link above.

**Comment by IgorGanapolsky** [comment]
Thanks.  If I need to know accuracy of beacon (like in iOS), will that be included in library?
