### ISSUE TITLE
Can we make one region consisting of all beacons?

### ISSUE THREAD

**Issue by sisreeksha** [AltBeacon/spec#23]
I am trying to get all beacons those are in my range, and for that I am using the "beaconManager.getRangingNotifier().didRangeBeaconsInRegion(Collection<Beacons> arg0, arg1);" method. I am trying to use arg1 parameter as a region consisting of all the beacons so that I get the 'beacons' collection filled up with just the beacons that are in proximity.

But I am not able to create a region with multiple beacons. When I use the region constructor with three ideantifiers and fill up those values with UUID, Major & Minor values of a particular beacon it is able to match. But whenever I am using the constructor with List<Identifier> version, and pass all the UUIDs, no matching happens. Please provide some guidance.

**Comment by davidgyoung** [comment]
Hi, @sisreeksha, please ask this question on StackOverflow.com as that is the proper forum for support of the open source Android Beacon Library.  

This forum is reserved for feedback comments on the AltBeacon specification.
