### ISSUE TITLE
Bluetooth intermittently crashes after several hours of AltBeacon broadcasts...

### ISSUE THREAD

**Issue by Keith3679** [AltBeacon/spec#26]
We are seeing the following Fatal Exception after hours of broadcasting an AltBeacon every 10s.  Not sure if this is related to the AltBeacon Native Libraries?

09-18 03:14:25.320 I/ActivityManager(27950): Process com.android.bluetooth (pid 31684) has died
09-18 03:14:25.320 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.hid.HidService in 1000ms
09-18 03:14:25.325 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.btservice.AdapterService in 1000ms
09-18 03:14:25.325 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.hfp.HeadsetService in 11000ms
09-18 03:14:25.325 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.a2dp.A2dpService in 11000ms
09-18 03:14:25.327 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.hdp.HealthService in 10998ms
09-18 03:14:25.327 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.pbap.BluetoothPbapService in 10998ms
09-18 03:14:25.328 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.gatt.GattService in 10997ms
09-18 03:14:25.328 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.opp.BluetoothOppService in 20997ms
09-18 03:14:25.328 W/ActivityManager(27950): Scheduling restart of crashed service com.android.bluetooth/.pan.PanService in 20997ms
09-18 03:14:25.329 E/AndroidRuntime(27950): **\* FATAL EXCEPTION IN SYSTEM PROCESS: main
09-18 03:14:25.329 E/AndroidRuntime(27950): java.lang.IllegalStateException: beginBroadcast() called while already in a broadcast
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.os.RemoteCallbackList.beginBroadcast(RemoteCallbackList.java:230)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at com.android.server.BluetoothManagerService$ProfileServiceConnections.onServiceDisconnected(BluetoothManagerService.java:680)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1213)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1227)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.os.Handler.handleCallback(Handler.java:739)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.os.Handler.dispatchMessage(Handler.java:95)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at android.os.Looper.loop(Looper.java:135)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at com.android.server.SystemServer.run(SystemServer.java:269)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at com.android.server.SystemServer.main(SystemServer.java:170)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at java.lang.reflect.Method.invoke(Native Method)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at java.lang.reflect.Method.invoke(Method.java:372)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
09-18 03:14:25.329 E/AndroidRuntime(27950):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by davidgyoung** [comment]
The Android Beacon Library has no native components.  It relies entirely on the bluetooth stack and APIs provided by Android.  The problem you report may indeed be an issue in Android or the firmware of a specific Android device.  There is very little this project can do to address that, and it would be better to open an issue with Android or the device manufacturer.  That said, it would be good to at least document 
which device model and OS build number where you are seeing that issue.

This issue is with the Android Beacon Library, so if you need to reopen, please create one here:  https://github.com/AltBeacon/android-beacon-library/issues
