### ISSUE TITLE
Extra Byte Received

### ISSUE THREAD

**Issue by GreyMark7650** [AltBeacon/spec#28]
I am trying to analyse the packet data I am receiving from two different AltBeacons (RadBeacon and easiBeacon). I have compared the received data with the sepcification and can match all except one byte.There seems to be one more byte than expected between the BLE header and the AltBeacon Advertisment. Since both beacons send the same format I could just ignore it I know, but it would be nice to know what the issue is. See below for the data packets. Any help would be appreciated.

MarkW

![image](https://cloud.githubusercontent.com/assets/4247250/10661483/3365dcfc-78a6-11e5-870a-bd8718414b83.png)

**Comment by davidgyoung** [comment]
The individual bits of that flags value have the following meanings:

```
 bit 0 LE Limited Discoverable Mode
 bit 1 LE General Discoverable Mode
 bit 2 BR/EDR Not Supported
 bit 3 Simultaneous LE and BR/EDR to Same Device Capable (controller)
 bit 4 Simultaneous LE and BR/EDR to Same Device Capable (Host)
```

In the first case, value 0x06 has "LE General Discoverable Mode" set and "BR/EDR Not Supported"

In the second case, value 0x04 has "BR/EDR Not Supported"

So the difference is basically that the RadBeacon is telling you it is configurable and the EZBeacon is not.

**Comment by GreyMark7650** [comment]
Thanks for the information on that byte. That isn't my issue though. The specification has only three bytes for flags - this is a fourth byte.

![image](https://cloud.githubusercontent.com/assets/4247250/10666112/8bd18226-78c7-11e5-9f08-8174e4cadb38.png)

MarkW

**Comment by davemradnet** [comment]
The first byte you have listed in AD Flags `0x1F` is not part of the AD Flags. It's the PDU length (31 bytes).

**Comment by GreyMark7650** [comment]
Thanks, I figured that out from this post:
https://devzone.nordicsemi.com/question/15801/s110-advertising-access-address-and-other-questions/

I still think that there is an error in the above diagram, but it relates to the BLE PDU part of the diagram. The "extra byte" should be shown between the 6 byte AvdA and 3 Byte AD Flags. It is as you say the length of the data for the next (and only) report.

MarkW

**Comment by davemradnet** [comment]
Glad you got it worked out, some additional, relatively minor points:
- The EasiBeacon appears to _mostly_ follow the iBeacon spec, not AltBeacon. However, the iBeacon spec has a length of `0x1A` not `0x1B` as the EasiBeacon is showing.
- The AltBeacon also specifies an additional byte not shown in your capture above (The MFG RSVD byte). This will often hold the battery level of beacons that are battery powered.
- Note that the RSSI is not part of the BLE Advertisement. That is, it is not part of the 31 bytes being advertised.
