### ISSUE TITLE
Vendor/Mfg code

### ISSUE THREAD

**Issue by zimbob10k** [AltBeacon/spec#36]
Hello,

My question is - should you use a SIG organizational identifier for the mfg code if you are generating ALT packets using Bluez?  

For example, I have a Broadcom BT4.0 adapter - its MAC state that it is part of the Broadcom OU.  I obviously don't manufacture the BT chip, but the device will be distributed under another company.  Should that company apply for a CIC and use that in the mfg field?

Thanks!

**Comment by davidhelms** [comment]
Ron,

In general, that is the intention.
It's expected that AltBeacon will be primarily implemented by beacon manufacturers.
It does give you the ability to recognize an advertisement that you have designed to use the last byte for some other purpose other than the battery level percentage.
Having said that, the Radius Networks SIG company id is 0x0118 and nobody is going to get too upset if you use that.
(Note that in the actual advertisement bytes the mfg code is in reverse order, so in the byte stream from first to last it is 0x18 0x01.)
