### ISSUE TITLE
What is "AD Flags"

### ISSUE THREAD

**Issue by SorenHN** [AltBeacon/spec#45]
What is the "AD Flags" field  depicted "BLE Advertising PDU" picture?
I cannot find any information regarding this data field in neither the Bluetooth specification or via internet searches.

As i read the picture, it seems like it is part of the ADV_IND PDU packet but no information points to ADV Flags being a part of this packet.

**Comment by SorenHN** [comment]
I figured it out.
If anyone has the same question as i had, you can read about it in [Bluetooth Core V 4.0](https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=229737&_ga=2.268038730.555326835.1503928041-320644414.1503306577) in Volume 3, Part C, Section 8.1.3.
And a specification off each flag in Volume 3, Part C, Section 18.1.

**Comment by ejaffrot** [comment]
Hi!
I have the same question as yours (5 years later!!!).
I checked the Core v4.0 and found some piece of explanation.
But all this disappeared in the core v5.2...
I can´t understand what's standardized to be in the 3 bytes AD Flag field...
Any more precise information?
Many thanks

**Comment by SorenHN** [comment]
Hi.
I haven't worked with this since 2017, so i can, unfortunately, not provide any more help.

**Comment by davidhelms** [comment]
From[ here](https://www.bluetooth.com/blog/advertising-works-part-2/)

```Flags
This is an important AD Type and it is almost always included in advertising packets (It can’t be included in scan response PDUs). It tells you about the advertising state of the device and which of the two transports, Bluetooth® low energy and Bluetooth BR/EDR it supports.

A device which is discoverable can either be in Limited Discoverable Mode or General Discoverable Mode. Limited Discoverable Mode is used to suggest that the device should have a high priority to scanning devices and often the advertising interval used when in this mode is faster than when in the General Discoverable Mode. A device will be in Limited Discoverable Mode for a limited time only and the core specification recommends this be no more than one minute. A device whose Flags field indicates it is not discoverable just means scanning devices should ignore it.
```

You would typically have the following 3 byte AD flags PDU in a beacon advetisement

```
Byte 0: Length :  0x02 (Length)
Byte 1: Type:     0x01 (Flags)
Byte 2: Value:    0x06 (Typical Flags 0b00000110) (LE General Discoverable Mode, BR/EDR Not Supported)
```

**Comment by ejaffrot** [comment]
Many thanks David,
Clear enough!
Cheers
