### ISSUE TITLE
How to get the Advertising Flags using Altbeacon lib?

### ISSUE THREAD

**Issue by yong3liu2** [AltBeacon/spec#48]
Using Altbeacon lib, I can see the beacons that I am looking for.  
            @Override
            public void didEnterRegion(Region region) { ...}

But I also need to read AD Flags such as following, for example:
02 # Number of bytes that follow in first AD structure
01 # Flags AD type
1A # Flags value 0x1A = 000011010  
   bit 0 (OFF) LE Limited Discoverable Mode
   bit 1 (ON) LE General Discoverable Mode
   bit 2 (OFF) BR/EDR Not Supported
   bit 3 (ON) Simultaneous LE and BR/EDR to Same Device Capable (controller)
   bit 4 (ON) Simultaneous LE and BR/EDR to Same Device Capable (Host)

Is there an API in Altbeacon lib to read the Flags?

Thanks,
Yong

**Comment by mdxs** [comment]
This is not a https://github.com/AltBeacon/spec specification question, please ask in the appropriate software oriented project if still a concern.
